### ISSUE TITLE
Problem in using Metaheuristic-based feature selection

### ISSUE THREAD

**Issue by MH-Abid** [thieu1995/mafese#2]
Whenever I am trying to use the following line of code- 
feat_selector.fit(data.X_train, data.y_train, fit_weights=(0.9, 0.1), verbose=True) 

I am getting the following error- 
ValueError: Found array with 0 feature(s) (shape=(5854, 0)) while a minimum of 1 is required by KNeighborsClassifier.

**Comment by thieu1995** [comment]
@MH-Abid ,

It is clear that your loaded data is not in correct format. Which dataset you are using? Also give the full script. I can check it for you.

**Comment by MH-Abid** [comment]
Thank you very much. Here is my full script.  


!pip install mafese==0.1.5

import pandas as pd
import numpy as np
from mafese import Data

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/Datasets/Diabeties Saudi/csv_converted.csv',index_col=False, header=None).values

df

X = df[: , 0:-1]
y= df[: , -1]

data = Data(X, y)

data.split_train_test(test_size=0.2, inplace=True)

print(data.X_train)
print(data.y_train)

#data.split_train_test(test_size=0.2, inplace=True)
print(data.X_train.shape)
print(data.y_train.shape)

from mafese.wrapper.mha import MhaSelector
from mafese import get_dataset, evaluator
from sklearn.svm import SVC

# define mafese feature selection method
feat_selector = MhaSelector(problem="classification", estimator="knn",
                            optimizer="BaseGA", optimizer_paras=None,
                            transfer_func="vstf_01", obj_name="AS")

# find all relevant features
feat_selector.fit(data.X_train,data.y_train, fit_weights=(0.9, 0.1), verbose=True) 









For your convenience, I am also sharing my dataset. Here is the link for the dataset: https://drive.google.com/file/d/1r6CektRkHnkVTCtg1wVO4r7vojo2NqRQ/view?usp=sharing

**Comment by thieu1995** [comment]
@MH-Abid , wow, I see.

I rememeber this problem. It is due to the BaseGA method is not using amend_solution before calculating fitness. Please install the latest version of mealpy by this way. 

`$ pip install mealpy==2.5.4a5`

Thank you

**Comment by thieu1995** [comment]
@MH-Abid ,

Or you can try any other algorithms, it will work. Only BaseGA method is not work.

**Comment by MH-Abid** [comment]
Thanks a lot. Using the Mealpy 2.5.4a5, it works. The library is very smart and well planned. Great work by you..

**Comment by thieu1995** [comment]
@MH-Abid ,

Thanks, please it a star. 
You should read the examples folder. There are a lots of methods that you can use. 
I don't claim this is the biggest feature selection library for fun. This is the truth.

**Comment by MH-Abid** [comment]
Surely. The library is very rich and intelligently planned...
