### ISSUE TITLE
can you explain the use of 'transfer_func' in feature selector?

### ISSUE THREAD

**Issue by Target2target** [thieu1995/mafese#4]
### Description

while using this 'MhaSelector' for feature selector, I can't figure out what is 'transfer_func' here.

**Comment by thieu1995** [comment]
Hi @Target2target ,

It comes from this paper: https://doi.org/10.1016/j.swevo.2012.09.002
The function you can set are: 
  - v-shape transfer function: "vstf_01", "vstf_02", "vstf_03", "vstf_04"
  - s-shape transfer function: "sstf_01", "sstf_02", "sstf_03", "sstf_04"

You can see the source code from here: https://github.com/thieu1995/mafese/blob/main/mafese/utils/transfer.py
